bot-manager:
  default: test
  setting:
    test:
      auto-login: false
      account: ""
      password: ""
send-load-finish-tip:
  enable: true
  message:
    - 'Wc-Bot 已加载完成!'
server-join-player:
  enable: true
  message: "%player_name%加入了服务器"
server-quit-player:
  enable: true
  message: "%player_name%离开了服务器"
server-to-qq-group:
  #服务器给群聊发送消息
  enable: false
  start-message: "群 "
  format: "%player%>>>%chat%"
  remove-color: true
  send-success-tip:
    #发送成功提示
    enable: true
    message: "消息发送成功~"
qq-group-to-server:
  #群聊给服务器发送消息
  enable: false
  # 是否开启
  start-message: "服 "
  # 检测开头关键字
  format: "[人工智障]%qq% %qq_nick% >>>%chat%"
  # 发送至群聊格式
  send-success-tip:
    enable: true
    message: "消息发送成功~"